### ISSUE TITLE
Inference not using GPU through Bonsai

### ISSUE THREAD

**Issue by MForsthofer** [bonsai-rx/sleap#15]
Hi, i'm trying to run a SLEAP single instance tracking node within a bonsai workflow and have issues getting it to use the GPU properly. I'll give some background on what i did so far to resolve a few issue because maybe some of those steps of installing and reinstalling software caused my current problem, and then describe the current issue.

So far: 
I've set up SLEAP in a python virtual environment, where it is working fine. I've trained and exported a model, and in principle the Bonsai node worked. But it performed the tracking with only the CPU, and thus far to slow (~11 fps) for online video tracking (doing inference on the videos directly in the SLEAP GUI did use the graphics card, a geforce 3060). The errors i got were all in this style:  
2023-07-19 17:05:50.946203: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
I ended up removing my current versions of tensorflow, CUDA and cuDNN, and installed tensorflow 2.10.0, CUDA v11.3 and cuDNN 8.2 (in the virtual env through miniconda, and in my base env through installs/copying .dlls into the bonsai extensions folder) as those were the last validated versions according to the bonsai/sleap install guide. 

Current state: 
Now bonsai/sleap detects  and initializes the GPU, but then crashes with the following errors in bonsai itself: 
Bonsai.WorkflowRuntimeException: 2 root error(s) found.
  (0) UNKNOWN: JIT compilation failed.
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/single_instance_inference_model_1/single_instance_inference_layer_1/PartitionedCall_1/mod}}]]
	 [[Identity_1/_49]]
  (1) UNKNOWN: JIT compilation failed.
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/single_instance_inference_model_1/single_instance_inference_layer_1/PartitionedCall_1/mod}}]]
0 successful operations.
0 derived errors ignored. ---> TensorFlow.TFException: 2 root error(s) found.
  (0) UNKNOWN: JIT compilation failed.
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/single_instance_inference_model_1/single_instance_inference_layer_1/PartitionedCall_1/mod}}]]
	 [[Identity_1/_49]]
  (1) UNKNOWN: JIT compilation failed.
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/single_instance_inference_model_1/single_instance_inference_layer_1/PartitionedCall_1/mod}}]]
0 successful operations.
0 derived errors ignored.
   at TensorFlow.TFStatus.CheckMaybeRaise(TFStatus incomingStatus, Boolean last)
   at TensorFlow.TFSession.Run(TFOutput[] inputs, TFTensor[] inputValues, TFOutput[] outputs, TFOperation[] targetOpers, TFBuffer runMetadata, TFBuffer runOptions, TFStatus status)
   at TensorFlow.TFSession.Runner.Run(TFStatus status)
   at Bonsai.Sleap.PredictSinglePose.<>c__DisplayClass20_1.<Process>b__1(IplImage[] input)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
   --- End of inner exception stack trace ---

And in the bonsai terminal: 
Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
2023-07-19 17:53:06.603435: W tensorflow/core/framework/op_kernel.cc:1768] UNKNOWN: JIT compilation failed.

I've since tried adding the CUDA/v8.2.0.51/nvvm/libdevice folder (in the base environment, not the virtual env) to either the PATH or to it's own CUDA_DIR environmental variable, but with no success. 
I know this is a rather lengthy one and i'm not super familiar with what i've been doing, so if anything is unclear just ask away. Any help in getting this to work would be much appreciated.

**Comment by bruno-f-cruz** [comment]
Can you attach the network and config file? Thanks

**Comment by MForsthofer** [comment]
Thanks for the fast reaction. I'm assuming with config file you mean the one in the bonsai directory, but could you explain what you mean with the network file?

**Comment by MForsthofer** [comment]
Here's the config file, plus the .json files of the model if that's what you mean with the network. 

https://gist.github.com/MForsthofer/cb22b5b3c20c8047fac2dd5d26cc299a

**Comment by MForsthofer** [comment]
Hey, i figured it out. The issue was that in my virtual environment i had tensorflow 2.7 installed, but the .dll i downloaded from https://www.tensorflow.org/install/lang_c as described in the install guide defaulted to the 2.10.0 version. Manually downloading version 2.7.0 through https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.7.0.zip and copying it into the bonsai directory solved the issue.

**Comment by MForsthofer** [comment]
Issue is now resolved
